### PR TITLE
add lycoris support

### PR DESCRIPTION
**Pull request by stdkoehler**
add support to download preview images for LyCORIS extension (https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris)

### CODE REVIEW

**Comment by JustMaier** [comment]
Oh, now that I'm reviewing this, I'm realizing that we already have support for LyCORIS [under the civitai internal name "LoCon"](https://github.com/civitai/sd_civitai_extension/blob/c6251a12120ac9f946fcaf8d9cb0a0f19176d9e6/civitai/lib.py#L201). Have you had trouble downloading things marked as LyCORIS through the link? Or were you just hoping to be able to have them download to a different directory?

**Comment by stdkoehler** [comment]
Hey there, I've seen the LoCon in the files but somehow it didn't work for me (probably because it looks into the Lora folder). For whatever reason the LyCORIS plugin uses a different folder for me (not sure if that's default or if I did something wrong). I never tried to just put the LyCORIS files into die Lora directory. Is that how it's supposed to be and how the plugin will download the preview images?

The directory created by the LyCORIS plugin is also accessible via these environment variables (shared.cmd_opts.lyco_dir), which seems to be created automatically.

**Comment by JustMaier** [comment]
I'm pretty sure I have the same extension and that it's reading my lycoris lora files out of the default lora folder. Do you perhaps also have the Kohya extension installed? I know that that makes it so that loras use a different directory.

Could you modify this PR to have it download the lycoris (locon) files to a separately specified lycoris directory (like you already have) with a fall back to the standard lora directory?

**Comment by stdkoehler** [comment]
This is the plugin I am using https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git (suggested for LyCORIS models by civitai).

I can sure try to adapt the PR. Just to verify: I remove the "LyCORIS" type that I introduced and instead use LoCon which is already there. Then we check whether shared.cmd_opts.lyco_dir is set. If so, we use it. If not, we use the lora directory?

**Comment by JustMaier** [comment]
That'd be great 🙏

**Comment by stdkoehler** [comment]
I tried to update according to your suggestions

**Comment by JustMaier** [comment]
Awesome, thanks for making those adjustments. We'll get this rolled into main after a round of tests

**Review by Jhonsshons — COMMENTED** [review]
civitai

**Review by Jhonsshons — APPROVED** [review]

**Review by Jhonsshons — APPROVED** [review]

**Pull request merged**
