### PR TITLE
Added Link status icon and reconnect on click. Added Lora info downlo…

### PR DESCRIPTION
**Pull request by jiveabillion**
…ad after adding from Civitai

### CODE REVIEW

**Comment by thiagojramos** [comment]
Sometimes it works, and other times it doesn't. When I press the heart icon button, it gives some UI errors. But thank you for providing this alternative version to the buggy main version of Civitai

<details><summary>Screenshots of some issues</summary>
<p>





</p>
</details>

**Comment by JustMaier** [comment]
@jiveabillion have you noticed the error that @thiagojramos mentioned? I'm happy to get this merged if it helps people recover connections. SocketIO has been so spotty :(

**Comment by jiveabillion** [comment]
I only sorta know what I'm doing. I'm a .NET dev with 16 years of
experience, but I had to learn some python to do this. I'm good at figuring
things out and this works well enough for my own use but I don't know how
to make it work better.

**Comment by jiveabillion** [comment]
Ok I looked closer at the screenshots and I think I know how to fix it.
I'll take a look at it tomorrow or soon when I find time during the
holidays

**Comment by fcolecumberri** [comment]
> @jiveabillion have you noticed the error that @thiagojramos mentioned? I'm happy to get this merged if it helps people recover connections. SocketIO inside of a1111 has been so spotty :(

I have noticed it.

**Comment by thiagojramos** [comment]
Thanks for fixing that. 😊 The reconnect function is working smoothly.

**Comment by JustMaier** [comment]
Thanks again @jiveabillion!

**Pull request merged**
